# mkdocs.yml

site_name: Obituário de Deuses
site_url: https://JoshSigil.github.io/  # 🔥 URL correta para site de usuário

# Tema e Customização Visual
theme:
  name: material
  features:
    - navigation.sections   # Permite organizar por categorias (já ativado)
    - toc.integrate 
  use_directory_urls: true

  # Paleta de Cores (Claro + Escuro)
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "#1d0031"    # Roxo profundo para tema claro
      accent: teal            # Destaques em verde-azulado
      background: white
      toggle:
        icon: material/weather-sunny
        name: Modo Noturno

    - media: "(prefers-color-scheme: dark)"
      scheme: dark           # Base escura pré-definida
      primary: black          # Preto fosco dominante
      accent: red             # Toques de vermelho-sangue
      background: "#B2BEB5" # Ash Gray
      toggle:
        icon: material/weather-night
        name: Modo Diurno

  # Fontes Personalizadas
  font:
    text: Roboto          # Fonte principal
    code: "Fira Code"     # Fonte para blocos de código

  # Logo e Favicon
  logo: assets/logo.png   # Caminho para sua logo (PNG/SVG)
  favicon: assets/favicon.ico

# CSS Customizado
extra_css:
  - stylesheets/extra.css


markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Plugins
plugins:
  - search  # Plugin padrão (obrigatório manter)
  - awesome-pages:  # 🗺️ Organização automática de páginas
      collapse_single_pages: false
  - markdownextradata:  # 🔄 Dados externos em templates
      data: docs/data

# Extras
extra:
  # Metadados para SEO
  site_description: "Regras e lore para a campanha Obituário de Deuses"
  
  # Links Externos no Header
  social:
    - icon: fontawesome/brands/discord
      link: "https://discord.gg/seulink"
    - icon: fontawesome/solid/book
      link: "https://worldanvil.com"

# Configurações de Build
strict: true  # Ativa verificações rigorosas
watch: []      # Ignora mudanças em arquivos específicos